---
exclude: ['README.markdown', 'Makefile', 'component.json']
pygments: true
safe: false

name: Foundation
url: http://unitech.github.io/foundation/
author: Bob Smith
email: bob@example.com
# ga: 'UA-XXXXXXX-X'
